-- AlterTable
ALTER TABLE `Cereal` MODIFY `calories` INTEGER NOT NULL DEFAULT 0,
    MODIFY `protein` INTEGER NOT NULL DEFAULT 0,
    MODIFY `fat` INTEGER NOT NULL DEFAULT 0,
    MODIFY `sodium` INTEGER NOT NULL DEFAULT 0,
    MODIFY `fiber` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `carbo` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `sugars` INTEGER NOT NULL DEFAULT 0,
    MODIFY `potass` INTEGER NOT NULL DEFAULT 0,
    MODIFY `vitamins` INTEGER NOT NULL DEFAULT 0,
    MODIFY `shelf` INTEGER NOT NULL DEFAULT 0,
    MODIFY `weight` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cups` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `rating` VARCHAR(191) NOT NULL DEFAULT 'empty';
